### ISSUE TITLE
erlang error while parsing a file

### ISSUE THREAD

**Issue by avila-gabriel** [katekyy/glaml#3]
```gleam
  let assert Ok(document) = glaml.parse_file("./dns.yml") // or "dns.yml"
    as "Yaml filepath is wrong"
```
the error happens during the parsing not at the assertion as there is no message from the "as" keyword in the output.
```powershell
   Compiled in 0.74s
    Running dns_config.main
runtime error: Erlang error

An error occurred outside of Gleam.

erlang:error(Badarg)

stacktrace:
  erlang.list_to_binary unknown source
  yaml_ffi.from_yamerl_node c:/Users/gabri/OneDrive/Área de Trabalho/dns_config/build/dev/erlang/glaml/_gleam_artefacts/yaml_ffi.erl:88
  yaml_ffi.from_yamerl_map_elem c:/Users/gabri/OneDrive/Área de Trabalho/dns_config/build/dev/erlang/glaml/_gleam_artefacts/yaml_ffi.erl:113
  yaml_ffi.from_yamerl_map_elems c:/Users/gabri/OneDrive/Área de Trabalho/dns_config/build/dev/erlang/glaml/_gleam_artefacts/yaml_ffi.erl:120
  yaml_ffi.from_yamerl_map_elems c:/Users/gabri/OneDrive/Área de Trabalho/dns_config/build/dev/erlang/glaml/_gleam_artefacts/yaml_ffi.erl:120
  yaml_ffi.from_yamerl_node c:/Users/gabri/OneDrive/Área de Trabalho/dns_config/build/dev/erlang/glaml/_gleam_artefacts/yaml_ffi.erl:100
  yaml_ffi.from_yamerl_nodes c:/Users/gabri/OneDrive/Área de Trabalho/dns_config/build/dev/erlang/glaml/_gleam_artefacts/yaml_ffi.erl:107
  yaml_ffi.from_yamerl_nodes c:/Users/gabri/OneDrive/Área de Trabalho/dns_config/build/dev/erlang/glaml/_gleam_artefacts/yaml_ffi.erl:107
```
the dns file:
```yaml
records:
  # --- LANDING PAGES (REGIONALIZED WITH LOCALIZED NAMES) ---
  - region: "us"
    service: "landing"
    subdomain: "carehelper.us.togetherhealth.com"
    localized_name: "CareHelper" # Localized name for the app in the US
    type: "CNAME"
    content: "landing-us.backend.example.com"
    proxied: true

  - region: "uk"
    service: "landing"
    subdomain: "healthguardian.uk.togetherhealth.com"
    localized_name: "HealthGuardian" # Localized name for the UK
    type: "CNAME"
    content: "landing-uk.backend.example.com"
    proxied: true

  - region: "jp"
    service: "landing"
    subdomain: "健康サポート.jp.togetherhealth.com"
    localized_name: "健康サポート" # "Health Support" in Japanese
    type: "CNAME"
    content: "landing-jp.backend.example.com"
    proxied: true

  - region: "fr"
    service: "landing"
    subdomain: "aidesoins.fr.togetherhealth.com"
    localized_name: "Aide Soins" # "Care Help" in French
    type: "CNAME"
    content: "landing-fr.backend.example.com"
    proxied: true

  - region: "de"
    service: "landing"
    subdomain: "gesundheitsdienst.de.togetherhealth.com"
    localized_name: "Gesundheitsdienst" # "Health Service" in German
    type: "CNAME"
    content: "landing-de.backend.example.com"
    proxied: true

  - region: "es"
    service: "landing"
    subdomain: "asistentecuidado.es.togetherhealth.com"
    localized_name: "Asistente Cuidado" # "Care Assistant" in Spanish
    type: "CNAME"
    content: "landing-es.backend.example.com"
    proxied: true

  - region: "it"
    service: "landing"
    subdomain: "assistenzasalute.it.togetherhealth.com"
    localized_name: "Assistenza Salute" # "Health Assistance" in Italian
    type: "CNAME"
    content: "landing-it.backend.example.com"
    proxied: true

  - region: "br"
    service: "landing"
    subdomain: "ajudasaude.br.togetherhealth.com"
    localized_name: "Ajuda Saúde" # "Health Help" in Brazilian Portuguese
    type: "CNAME"
    content: "landing-br.backend.example.com"
    proxied: true

  - region: "in"
    service: "landing"
    subdomain: "carebuddy.in.togetherhealth.com"
    localized_name: "CareBuddy" # Localized name for India
    type: "CNAME"
    content: "landing-in.backend.example.com"
    proxied: true

  # --- SINGLE GATEKEEPER SUBDOMAIN ---
  - service: "gatekeeper"
    subdomain: "gatekeeper.togetherhealth.com"
    type: "CNAME"
    content: "gatekeeper.backend.example.com"
    proxied: true

  # --- SINGLE API SUBDOMAIN ---
  - service: "api"
    subdomain: "api.togetherhealth.com"
    type: "CNAME"
    content: "api.backend.example.com"
    proxied: true

  # --- SINGLE APP SUBDOMAIN ---
  - service: "app"
    subdomain: "app.togetherhealth.com"
    type: "CNAME"
    content: "app.backend.example.com"
    proxied: true
```
the error won't happen if the file is empty.
I'm on windows
```powershell
Erlang/OTP 26 [erts-14.2.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Eshell V14.2.3 (press Ctrl+G to abort, type help(). for help)
```
the problem sure is in `健康サポート` as its removal solved the error. They are encoded in UTF-8 with three bytes each and their unicode codepoints are: U+5065, U+5EB7, U+30B5, U+30DD, U+30FC, U+30C8. The file being encoded as UTF-8 or UTF-16 resulted in the same error.

The yaml_ffi.erl file that the stacktrace refers to, if any useful...
```erl
-module(yaml_ffi).

-export([parse_file/1, parse_string/1]).

-include_lib("yamerl/include/yamerl_errors.hrl").

-type yamerl_doc() :: any().

-type doc_error() :: {doc_error, binary(), {integer(), integer()}}.
-type document() :: {document, list(doc_node())}.
-type doc_node() ::
    {doc_node_map, list({doc_node(), doc_node()})}
    | {doc_node_seq, list(doc_node())}
    | {doc_node_str, binary()}
    | {doc_node_bool, boolean()}
    | {doc_node_int, integer()}
    | {doc_node_float, float()}
    | doc_node_nil.

% public
-spec parse_file(Path :: binary()) -> {ok, document()} | {error, doc_error()}.
parse_file(Path) ->
    hande_yamerl_result(file_detailed(Path)).

% public
-spec parse_string(String :: binary()) -> {ok, document()} | {error, doc_error()}.
parse_string(String) ->
    hande_yamerl_result(string_detailed(String)).

-spec hande_yamerl_result(Res :: {ok, yamerl_doc() | empty_doc} | {error, yamerl_error()}) ->
    {ok, document()} | {error, doc_error()}.
hande_yamerl_result(Res) ->
    case Res of
        {ok, YamerlDoc} ->
            {ok, from_yamerl(YamerlDoc)};
        {error,
            {yamerl_parsing_error, _Type, Message, undefined, undefined, _Name, _Token, _Extra}} ->
            {error, {doc_error, list_to_binary(Message), {0, 0}}};
        {error, {yamerl_parsing_error, _Type, Message, Line, Column, _Name, _Token, _Extra}} ->
            {error, {doc_error, list_to_binary(Message), {Line, Column}}};
        {error, {yamerl_invalid_option, _Type, Message, _Option}} ->
            {error, {doc_error, list_to_binary(Message), {0, 0}}}
    end.

-spec string_detailed(String :: binary()) ->
    {ok, yamerl_doc() | empty_doc} | {error, yamerl_error()}.
string_detailed(String) ->
    try
        case yamerl_constr:string(String, [{detailed_constr, true}]) of
            [YamerlDoc] -> {ok, YamerlDoc};
            [] -> {ok, empty_doc}
        end
    catch
        throw:#yamerl_exception{errors = Errors} ->
            [First | _] = Errors,
            {error, First}
    end.

-spec file_detailed(Path :: binary()) ->
    {ok, yamerl_doc() | empty_doc} | {error, yamerl_error()}.
file_detailed(Path) ->
    try
        case yamerl_constr:file(Path, [{detailed_constr, true}]) of
            [YamerlDoc] -> {ok, YamerlDoc};
            [] -> {ok, empty_doc}
        end
    catch
        throw:#yamerl_exception{errors = Errors} ->
            [First | _] = Errors,
            {error, First}
    end.

-spec from_yamerl(YamerlDoc :: yamerl_doc()) -> document().
from_yamerl(YamerlDoc) ->
    case YamerlDoc of
        {yamerl_doc, RootNode} ->
            {document, from_yamerl_node(RootNode)};
        empty_doc ->
            {document, {doc_node_seq, []}}
    end.

-spec from_yamerl_node(YamerlNode :: any()) -> doc_node().
from_yamerl_node(YamerlNode) ->
    case YamerlNode of
        {yamerl_null, yamerl_node_null, _, _Line} ->
            doc_node_nil;
        {yamerl_str, yamerl_node_str, _, _Line, String} ->
            {doc_node_str, list_to_binary(String)};
        {yamerl_bool, yamerl_node_bool, _, _Line, true} ->
            {doc_node_bool, true};
        {yamerl_bool, yamerl_node_bool, _, _Line, false} ->
            {doc_node_bool, false};
        {yamerl_int, yamerl_node_int, _, _Line, Integer} ->
            {doc_node_int, Integer};
        {yamerl_float, yamerl_node_float, _, _Line, Float} ->
            {doc_node_float, Float};
        {yamerl_seq, yamerl_node_seq, _, _Line, Elements, _Count} ->
            {doc_node_seq, from_yamerl_nodes(Elements)};
        {yamerl_map, yamerl_node_map, _, _Line, Elements} ->
            {doc_node_map, from_yamerl_map_elems(Elements)}
    end.

-spec from_yamerl_nodes(YamerlNodes :: list(any())) -> list(doc_node()).
from_yamerl_nodes(YamerlNodes) ->
    case YamerlNodes of
        [] -> [];
        [Elem | Tail] -> [from_yamerl_node(Elem) | from_yamerl_nodes(Tail)]
    end.

-spec from_yamerl_map_elem(YamerlElem :: any()) -> {doc_node(), doc_node()}.
from_yamerl_map_elem(YamerlElem) ->
    case YamerlElem of
        {Key, Value} -> {from_yamerl_node(Key), from_yamerl_node(Value)}
    end.

-spec from_yamerl_map_elems(YamerlMapElems :: list(any())) -> list({doc_node(), doc_node()}).
from_yamerl_map_elems(YamerlMapElems) ->
    case YamerlMapElems of
        [] -> [];
        [Elem | Tail] -> [from_yamerl_map_elem(Elem) | from_yamerl_map_elems(Tail)]
    end.
```
